name: Register Resource Providers

on:
  push:
    branches:
      - main

jobs:
  register-resource-providers:
    runs-on: ubuntu-latest
    environment: Sandbox

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CRED }}
        enable-AzPSSession: true

    - name: Run Azure PowerShell
      uses: Azure/powershell@v1
      with:
        inlinescript: .\deploy.ps1
        azPSVersion: 'latest'
